// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/test-report/MockReport.tsx": () => import("../components/mockups/test-report/MockReport.tsx")
};
